version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING=Host=aws-0-eu-north-1.pooler.supabase.com;Port=6543;Database=postgres;Username=postgres.wkzkiurvoslbhpmxmpid;Password=SS8CGDEssyk0AH8N;SSL Mode=Require;Trust Server Certificate=true;Multiplexing=false;
    ports:
      - "5000:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres.wkzkiurvoslbhpmxmpid
      POSTGRES_PASSWORD: SS8CGDEssyk0AH8N
      POSTGRES_DB: postgres
    ports:
      - "6543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
